### ISSUE TITLE
A few issues ... no names, no pictures, constant notifications

### ISSUE THREAD

**Issue by MacSass** [ohari5336/WhatsAllApp-Mod#14]
Hi, great to see this update - this comes as early christmas present ...

I experience some issues though, that I wanted to report:
- After adding the numbers to the list manually, the status picture and name does not show, they show as grey area only

![grafik](https://user-images.githubusercontent.com/25532047/102993601-c0720c80-451d-11eb-8c63-fe56726de988.png)

- The desktop notification pops up about every second when a user is only, instead of only just once

One wish: Add options dialogue to enable / disable popups and sound notification (I have done this for a small extension I wrote for me, I can help with that if you wish).

As said - happy that you found time to continue on this.

Regards

**Comment by ohari5336** [comment]
Ohh thanks for appreciating me
pictures, name, status under maintenance soo please wait for this and your last problem **constant notifications** I try to solve this today

also, share your code and save my time...

**Comment by MacSass** [comment]
Hi, hope you had a good christmas (if you celebrate) ... did you have a chance to look into the issue of constant notification every second, when a user is online?

Thanks - MacSass

**Comment by ginevra2013** [comment]
news?
