### ISSUE TITLE
WhatsAllApp Mod  Community Defekt 

### ISSUE THREAD

**Issue by Orsuor737** [ohari5336/WhatsAllApp-Mod#16]
WhatsAllApp Mod
  Community
The extension starts with Chrome, you enter 1 number and look for the extension crashes.
stopping and restarting the extension does not help either.
tested on iMac and windows both does not work
Thank you for helping to solve the problem

**Comment by ohari5336** [comment]
WhatsApp again change its code

**Comment by Orsuor737** [comment]
Thank You for Info

**Comment by ginevra2013** [comment]
> WhatsApp again change its code


Hello, didn't you have to plan for us who made the donation? I look forward to hearing from you. Thank you

**Comment by ohari5336** [comment]
Sorry, but according to me this is illegal (you track anyone without asking them). Also I created this only for educational purposes not for spy.

So, Now I never update this repository

**Comment by ginevra2013** [comment]
But you asked for 100 dollars which we sent you. Good boy! You are correct!

Il giorno ven 25 feb 2022 alle ore 16:39 Hari Om Batra <
***@***.***> ha scritto:

**Comment by ohari5336** [comment]
I never asked anyone for any money please show message

**Comment by ginevra2013** [comment]
Scusa, ho sbagliato persona. Scusa. Buona giornata

Il ven 25 feb 2022, 17:29 Hari Om Batra ***@***.***> ha
scritto:

**Comment by ohari5336** [comment]
It's ok
