### ISSUE TITLE
automation: Set attribute value of the input for phone number list?

### ISSUE THREAD

**Issue by mathe1** [ohari5336/WhatsAllApp-Mod#2]
Hello, 

I did a fork of your project.
Now I want to collect the phone numbers of my buddies automatically and send the list as comma-separated string to the input-field.

At code in bundle.js I added an ID to the field, so I find it with getElementById.
Then I tried to set the attribute _value_ of the input.

That works short time, but then the input switch back to the value before. It only works when I type-in the phonenumber-list or paste the string there manually.
It seems be the function _onListValChange_ (but I don't understand the React-components).

How to do changes at the code for set the attribute _value_ by e.g. element.value="123,456,789" ??

**Comment by ohari5336** [comment]
Where your phone numbers list?

**Comment by mathe1** [comment]
At the orange overlay (of the extension) on the right side box.

**Comment by ohari5336** [comment]
Please share you script then I complete your code

**Comment by mathe1** [comment]
[Attached the part from bundle.js,](https://github.com/ohari5336/WhatsAllApp-Mod/files/4118880/extract_from_bundle_js.txt) where I added the ID for the input ("mathe1edit") and for button ("mathe1btn"). 

I think, this `onChange: this.onListValueChange` set back an injected string. 
If remove, the string will not remove but don't read at submit, too. So something inside the function should change...


After collect the phone-numbers to _phn_ I do:

`
var ped=document.getElementById('mathe1edit');
if (ped) 
{
    ped.value=phn;
    document.getElementById('mathe1btn').click();
 }     
`

_ped_ is the input.

**Comment by mathe1** [comment]
Okay,
I solved my problem by adding buttons with this function, works fine.
[https://github.com/mathe1/WhatsAllApp-Mod](https://github.com/mathe1/WhatsAllApp-Mod)
