### ISSUE TITLE
Slider not showing 

### ISSUE THREAD

**Issue by pcintra11** [ohari5336/WhatsAllApp-Mod#22]
I've installed the extension and reload the page. The icon is orange and it seems to be ok, but the slider is not showing. Why?
I even can enable and disable by the extension icon.
Tks for your attention.

**Comment by ohari5336** [comment]
WhatsApp again changed its code so when you run extension then mismatch object crash our extension

**Comment by pcintra11** [comment]
Ok, tks for your reply
