### ISSUE TITLE
when i add this on chrome. this err found

### ISSUE THREAD

**Issue by gokulhans** [ohari5336/WhatsAllApp-Mod#30]
Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

{
  "name": "WhatsAllApp Community Edition",
  "version": "2.0",
  "description": "UI overlay for WhatsApp Web to enumerate phone numbers, profile pics, online statuses and status texts.",
  "permissions": ["declarativeContent", "activeTab", "storage"  ],
  "background": {
    "scripts": ["background.js"],
    "persistent": false
  },
  "content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self'",
  "web_accessible_resources" : ["/bundle.js","note.mp3"],
  "manifest_version": 2,
  "page_action": {
    "default_popup": "popup.html",
    "default_icon": {
      "16": "images/icon_16x.png",

**Comment by ohari5336** [comment]
Sorry, We no longer maintain this project
