### ISSUE TITLE
post the compiled extension

### ISSUE THREAD

**Issue by ericsia** [ohari5336/WhatsAllApp-Mod#32]
Can you attach the compiled package to releases?
Currently 
```
gyp ERR! node -v v16.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
Build failed with error code: 7
```

**Comment by ohari5336** [comment]
Sorry, main source files of NodeJS old but dist folder latest compiled code

But whatsapp change self code soo our extention code not worked 

Don't ask for countinue this repo
