### ISSUE TITLE
User is shown online continiously

### ISSUE THREAD

**Issue by nityoday** [ohari5336/WhatsAllApp-Mod#5]
After the user has come online, it updates correctly, but even after they leave and go offline, this shows online with a green box around them, a clock with current time and "a few seconds ago" written over there. [This happens quite a lot of times but not always]

After I refresh the page it starts working back normally and shows never.

**Comment by ohari5336** [comment]
after the user goes offline its show green box a few minutes then goes normal please wait some minutes you also see in your browser console in real-time.

**Comment by nityoday** [comment]
Yeah that's how it's supposed to work and it does, most of the times, but sometimes it just doesn't update and keeps showing that green box indefinitely until refreshed. That's the issue.

**Comment by ginevra2013** [comment]
Good morning Ohari5336, Whatsapp all does not work, you have updates, thanks for your availability and professionalism

**Comment by ohari5336** [comment]
> Good morning Ohari5336, Whatsapp all does not work, you have updates, thanks for your availability and professionalism

What's the error?

**Comment by ohari5336** [comment]
> Yeah that's how it's supposed to work and it does, most of the times, but sometimes it just doesn't update and keeps showing that green box indefinitely until refreshed. That's the issue.

please debug it and see which condition is shown green box all time

**Comment by ginevra2013** [comment]
Yes, sometimes it doesn't update and then the application starts, but today
it doesn't work. There are no error codes. Green screen only and does not
load the extension. I send you the screenshot of my version, which has
always worked.

Il giorno ven 27 mar 2020 alle ore 12:07 Hari Om Batra <
notifications@github.com> ha scritto:

**Comment by ginevra2013** [comment]
Versione 80.0.3987.149 (Build ufficiale) (a 64 bit)
Windows 10 pro

Il giorno ven 27 mar 2020 alle ore 12:45 Carmine Langella <
carmine.langella@gmail.com> ha scritto:

**Comment by ohari5336** [comment]
I got error please wait until the new update

**Comment by ginevra2013** [comment]
Thanks

Il giorno ven 27 mar 2020 alle ore 14:30 Hari Om Batra <
notifications@github.com> ha scritto:

**Comment by Reliktor1973** [comment]
Hi,
Yesterday 22:00 i think Whatsapp change api

I have this  Error:

Failed to load resource: the server responded with a status of 404 ()
14:10:12.799 WWapApi.js:55 Uncaught (in promise) TypeError: window.webpackJsonp is not a function
    at readMore (WWapApi.js:55)

This Line is it:

 var WLAPWAPStore = window.webpackJsonp([], null, ["bihdhbjih"]).default;

i hope you can fix thx

**Comment by ohari5336** [comment]
yes I found this

**Comment by ginevra2013** [comment]
You can send me the new file when it is ready
Very very Thanks

Il giorno ven 27 mar 2020 alle ore 14:56 Hari Om Batra <
notifications@github.com> ha scritto:

**Comment by nityoday** [comment]
> > Yeah that's how it's supposed to work and it does, most of the times, but sometimes it just doesn't update and keeps showing that green box indefinitely until refreshed. That's the issue.
> 
> please debug it and see which condition is shown green box all time

I'm not sure how to debug it? I am currently using your extension with chrome browser.

**Comment by ohari5336** [comment]
Check the new beta update, this is testing mode code soo maybe not working properly. [New Update](https://github.com/ohari5336/WhatsAllApp-Mod/tree/ohari5336-patch-1)

And also support me for future updates...

Sorry for the bad English...
