### ISSUE TITLE
Drag bar not appearing

### ISSUE THREAD

**Issue by emptyfullniss** [ohari5336/WhatsAllApp-Mod#6]
Hi I used this mod for quite a while with succes.
Not working anymore.... Maybe an update?

Extension is enabled as usual but not getting the bar in display anymore

**Comment by ohari5336** [comment]
I got error please wait until the new update

**Comment by MacSass** [comment]
Hi @ohari5336 , 
thanks - looking forward to the new update as I have the same issue: Orange bar is gone ...
Also, for me it looks like it already stopped showing online status some days ago ... when bar was still there.

Thanks for your efforts - MacS

**Comment by mathe1** [comment]
It is because something was changed:
Uncaught (in promise) TypeError: window.webpackJsonp is not a function
    at readMore (WWapApi.js:55)

How to fix that error?

**Comment by RoelWKramer** [comment]
That is an array now. But i discovered also the function name got changed.

Thanks for fixing!

**Comment by ginevra2013** [comment]
news?

**Comment by mathe1** [comment]
At my mod I added a simple tracker with audio, so the extension is not useless ;-)

**Comment by themayk** [comment]
Brother, there is a progress, we look forward to the update.

**Comment by 100n0m3** [comment]
@RoelWKramer share the function name please

**Comment by CodeCloomy** [comment]
news? how to find the function name?

**Comment by ginevra2013** [comment]
There are updates?

**Comment by WorldCrow** [comment]
Hi
the software is not running ???
no update ???

**Comment by asadkhansohail** [comment]
> I got error please wait until the new update

Waiting, thanks

**Comment by CoraatB3ware** [comment]
It's really too bad because this was a great project. But the maintenance effort to follow up on changes is probably too great. 
@ohari5336: Can you give us a short Feedback if there will be further development or if the Project is closed? Thx in advance.

**Comment by mathe1** [comment]
Hey @ohari5336  - let us help you.
Do you have any interim results? 

If we know how to inspect the code (searching for what functionallity), we could all together finding the required function to update our extension...?

I find the old function's name is still in the code, but - like @RoelWKramer said, it is an array now. So, is there anything useful in that array, we could write an own function, or not?

**Comment by ohari5336** [comment]
sorry everyone, due to more workload I am too busy and I have no time to find updated function. and I don't know how long I will not be able to support.
if anyone found the updated function then please share it with us.

@RoelWKramer if you found any more details, please share

and this project not closed it's only on hold
after issue fix, I restart development of these features [What's Next](https://github.com/ohari5336/WhatsAllApp-Mod#whatsallapp-mod)

thanks for waiting

**Comment by ohari5336** [comment]
![image](https://user-images.githubusercontent.com/22674877/97951723-2913f700-1dc1-11eb-8129-38a2004f6609.png)


Hello Everyone, our code ready to work again I find WhatsApp new objects I try to update this repo in the next week soo I am now too excited to create now too many features, and some advanced features now also available in the future.

**Comment by CoraatB3ware** [comment]
@ohari5336 Thanks for the update - really great news. Waiting full of anticipation ... ;-)

**Comment by 100n0m3** [comment]
any news?

**Comment by ohari5336** [comment]
Sorry guys I am busy on some other projects soo I have no time to fix other bugs and upload here but wait I will try to upload here quickly.

**Comment by AttilaZang** [comment]
Waiting full of anticipation

**Comment by ohari5336** [comment]
Check the new beta update, this is testing mode code soo maybe not working properly. [New Update](https://github.com/ohari5336/WhatsAllApp-Mod/tree/ohari5336-patch-1)

And also support me for future updates...

Sorry for the bad English...
