### ISSUE TITLE
Not working!

### ISSUE THREAD

**Issue by smarteutech** [ohari5336/WhatsAllApp-Mod#7]
Hi!
There many github repo with javascript is working, There any chance to get update of this one?
Thanks!

**Comment by mathe1** [comment]
Hi,
please look at issue #6 - we all waiting for a solution, but when WhatsApp do an update, we start again for fixing.

Maybe you find my tracker helpful until we get the update..
https://github.com/mathe1/WhatsAppOnlineTracker

**Comment by ohari5336** [comment]
Check the new beta update, this is testing mode code soo maybe not working properly. [New Update](https://github.com/ohari5336/WhatsAllApp-Mod/tree/ohari5336-patch-1)

And also support me for future updates...

Sorry for the bad English...
